apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: datree
spec:
  version: v0.1.0
  homepage: https://github.com/datreeio/kubectl-datree
  shortDescription: Scan your k8s files within the cluster for misconfigurations
  description: |
    Datree is a static code analysis tool for k8s files. This plugin extends the tool's capabilities
    to allow scanning k8s yaml files within the cluster for misconfigurations.
  caveats: |
   
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    uri: https://github.com/datreeio/kubectl-datree/.../v0.9.4.tar.gz
    sha256: 2125a043ea3f78379a601de82e6a4cb5778f9f988634bf1e02a63566411ac81d
    bin: kubectl-datree