apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: datree
spec:
  version: {{ .TagName }}
  homepage: https://github.com/datreeio/kubectl-datree
  shortDescription: Scan your cluster resources for misconfigurations
  description: |
    Datree is a static code analysis tool for kubernetes manifest files.
    This plugin allows scanning resources within your cluster for misconfigurations.
  caveats: |
    Before using this plugin, the Datree CLI needs to be installed.
    See https://hub.datree.io/ for quick and easy installation.
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    {{addURIAndSha "https://github.com/datreeio/kubectl-datree/releases/latest/download/kubectl-datree.zip" .TagName }}
    files:
    - from: "kubectl-datree"
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-datree
    
