apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: datree
spec:
  version: v0.0.3
  homepage: https://github.com/datreeio/kubectl-datree
  shortDescription: Scan the resources within your cluster for misconfigurations
  description: |
    Datree is a static code analysis tool for k8s manifest files. This plugin extends the tool's capabilities
    to allow scanning resources within your cluster for misconfigurations.
  caveats: |
   
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    uri: https://github.com/datreeio/kubectl-datree/releases/download/v0.0.3/kubectl-datree.zip
    sha256: "ffabb0dae0662ea8259f3f5e32ab18dae2caa16adbe66fd98ddb07ebbb216ba0"
    files:
    - from: "kubectl-datree"
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-datree
